### ISSUE TITLE
cannot add a comma before the year

### ISSUE THREAD

**Issue by damienchallet** [ShiroTakeda/econ-bst#1]
Hi

I need to have references in the following format: Bansal, R., and A. Yaron, 2004, Risks for the Long Run [...]

Thus, I have set 

% The string before year only for aritcle type entry.
%
FUNCTION {bst.year.pre}
{ ", " }
% { " (" }    % (default)

Yet, the output lacks the comma before the year, for example

Vuong, Q. H. 1989, Likelihood ratio tests

This seems to be a bug. 

Thanks for your help

**Comment by damienchallet** [comment]
I should add that the following works

FUNCTION {bst.year.pre}
{ ",, " }
% { " (" } % (default)

**Comment by ShiroTakeda** [comment]
Hi

The alternative solution may be that you change the definition of bst.author.post to the following,

FUNCTION {bst.author.post}
{ "," }
% { "" }    % (default)


If you find other problems, let me know.

Regards,

**Comment by damienchallet** [comment]
Indeed !

Thank you for your answer and for your work, which is _very_ useful.
