### ISSUE TITLE
error when Doi field is present

### ISSUE THREAD

**Issue by andreamoro-git** [ShiroTakeda/econ-bst#2]
Hi Shiro,
when some fields are present your style produces an error, for example, using econ-aer.bst, this entry (downloaded directly from google scholar with bibdesk) gives me an error:

```
@incollection{mcfadden1984,
	Abstract = {Publisher Summary
This chapter has surveyed the current state of econometric models and methods for the analysis of qualitative dependent variables. It discusses that the models of economic optimization that are presumed to govern conventional continuous decisions are equally appropriate for the analysis of discrete response. While the intensive marginal conditions associated with many continuous decisions are not applicable, the characterization of economic agents as optimizers implies conditions at the extensive margin and substantive restrictions on functional form. Unless the tenets of the behavioral theory are themselves under test, it is good econometric practice to impose these restrictions as maintained hypotheses in the construction of discrete response models. As a formulation in terms of latent variable models makes clear, qualitative response models share many of the features of conventional econometric systems. Thus the problems and methods arising in the main stream of econometric analysis mostly transfer directly to discrete response. Divergences from the properties of the standard linear model arise from nonlinearity rather than from discreteness of the dependent variable. Thus, most developments in the analysis of nonlinear econometric systems apply to qualitative response models. In summary, methods for the analysis of qualitative dependent variables are part of the continuing development of econometric technique to match the real characteristics of economic behavior and data.},
	Author = {Daniel L. McFadden},
	Booktitle = {Handbook of Econometrics Chapter 24 },
	Date-Added = {2018-12-31 16:16:11 +0100},
	Date-Modified = {2018-12-31 16:16:37 +0100},
	Doi = {https://doi.org/10.1016/S1573-4412(84)02016-X},
	Issn = {1573-4412},
	Pages = {1395 - 1457},
	Publisher = {Elsevier},
	Series = {Handbook of Econometrics},
	Title = {Econometric analysis of qualitative response models},
	Url = {http://www.sciencedirect.com/science/article/pii/S157344128402016X},
	Volume = {2},
	Year = {1984},
	Bdsk-Url-1 = {http://www.sciencedirect.com/science/article/pii/S157344128402016X},
	Bdsk-Url-2 = {https://doi.org/10.1016/S1573-4412(84)02016-X}}
```

**Comment by ShiroTakeda** [comment]
Hi

Thank you for reporting a problem. However, I cannot reproduce your problem. Will you tell me what kind of error you face? In addition, will you upload .blg file (BibTeX log file) and .log file (TeX log file)?

**Comment by andreamoro-git** [comment]
Here, I was finally able to reproduce it again

[Archive.zip](https://github.com/ShiroTakeda/econ-bst/files/2752115/Archive.zip)

**Comment by ShiroTakeda** [comment]
Hi 

I am sorry for the late reply.

In action_plan.log you sent to me, the following error occurs:

(./action_plan.bbl
./action_plan.bbl:13: Undefined control sequence.
l.13   \href
            {http://dx.doi.org/https://doi.org/10.1016/j.annepidem.2012.07.0...

? 

This means that you use \href command which is undefined.

In the default setting, econ.bst use \href command for showing DOI field. So you need to load hyperref package in the preample as follows

\usepackage{hyperref}


In addition, your bib file has one problem. In your bib file, you set DOI field as follows

DOI = {https://doi.org/10.1016/j.annepidem.2012.07.0}

However, econ.bst requires us to use the following format.

DOI = {10.1016/j.annepidem.2012.07.0}

If you use econ.bst, please use the latter format for DOI field.

**Comment by andreamoro-git** [comment]
got it. THe DOI field is as it comes out of google scholar
