### ISSUE TITLE
Bad characters in econ-jet and econ-jie files

### ISSUE THREAD

**Issue by fbrustolin** [ShiroTakeda/econ-bst#3]
In commit 78823755d74da5e443eaa08c71085b93bd87b49d (29 Mar 2020), a "nn" was inserted in the beggining of the first line of "customization/econ-jet.bst", which generates an error when trying to use this style.

In the same commit a "n" was inserted in file "customization/econ-jie.bst", but in this file the extra "n" was removed in commit 1b6ef410af3e88d306031ac05f23718d61e31d8c (23 May 2021).

I didn't try to figure out the reason, but I looked in the changelog, the readme, and the header of the file and found no clue of why those characters were inserted or removed.

Finally, I would like to know if it is safe to remove those "nn" and use the file or if they are there just to prevent people from using it while some error is not fixed.

**Comment by ShiroTakeda** [comment]
"nn" (and "n") is just my mistake. I have not noticed this. Thank you for reporting. I will fix this.
